modoboa/modoboa

doc/getting_started/upgrade.rst

Provides a warning about the sitestatic move.

Update upgrade.rst to warn about the sitestatic change

---

modoboa/extensions/webmail/forms.py
modoboa/extensions/webmail/templates/webmail/compose.html
modoboa/extensions/webmail/validators.py

fixed #413 email checking for to/cc/cci in webmail

fixed #413 email checking for to/cc/cci in webmail

---

modoboa/extensions/stats/graphics.py
modoboa/extensions/stats/management/commands/logparser.py

Add support for gathering statistics about spam and virus emails.

Gather statistics for spam and virus messages

---

modoboa/static/js/jquery.htmltable.js

This is now the same behavior than a famous webmail.

Improved: mail selection in shift mode.

---

modoboa/locale/de/LC_MESSAGES/django.po

Sorry, forgot to include this in the earlier PR.

Revise German translation.

---

modoboa/core/app_settings.py
modoboa/lib/exceptions.py
modoboa/lib/fetch_parser.py
modoboa/lib/imaputils.py

Fix https://github.com/modoboa/modoboa-sievefilters/issues/4 append imaputils to modoboa main repository

Append imaputils to modoboa main repository

---

modoboa/core/models.py

Fix permission bug if superuser execute import

Fix permission bug if superuser execute import

---

modoboa/lib/form_utils.py

The value of the for attribute must match the id of the input tag

Fix incorrect label tag

---

modoboa/core/app_settings.py

Append « in seconds » in « Top notifications check interval » field help message.

Append « in seconds » in « Top notifications check interval » field help message

---

modoboa/core/extensions.py
modoboa/lib/form_utils.py

Fix check new versions bug if modoboa is offline (example in train)

Fix check new versions bug if modoboa is offline

---

modoboa/core/commands/templates/settings.py.tpl
modoboa/core/dev_settings.py
modoboa/core/forms.py
modoboa/core/templates/core/user_profile.html
modoboa/core/tests.py
requirements.txt

Passwords complexity rules.

---

modoboa/core/migrations/0004_auto_20150728_1228.py
modoboa/core/models.py

Append database index to user table, the more important is index together email/is_active

Append database index to user table, the more important is index together email/is_active

---

README.rst

See:
* http://getbootstrap.com/about/#name
* https://github.com/twbs/bootstrap/issues/9899

Bootstrap is no longer affiliated with Twitter

---

modoboa/core/forms.py
modoboa/core/migrations/0006_auto_20151114_1518.py
modoboa/core/models.py

New profile fields

---

modoboa/core/forms.py
modoboa/core/migrations/0007_auto_20151116_1349.py
modoboa/core/models.py
modoboa/core/tests.py
modoboa/core/views/auth.py

Redirect user to profile on first login.

---

modoboa/admin/lib.py
modoboa/admin/migrations/0003_auto_20151118_1215.py
modoboa/admin/tests/export.py
modoboa/core/api.py
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/forms.py
modoboa/core/models.py
modoboa/core/serializers.py
modoboa/core/templates/core/api_access.html
modoboa/core/templates/core/user_index.html
modoboa/core/templates/core/user_profile.html
modoboa/core/templatetags/core_tags.py
modoboa/core/tests.py
modoboa/core/urls.py
modoboa/core/urls_api.py
modoboa/core/views/user.py
modoboa/lib/parameters.py
modoboa/lib/tests.py
modoboa/limits/migrations/0002_auto_20151114_1518.py
modoboa/static/js/global.js
modoboa/static/js/twocols_nav.js
modoboa/urls.py
modoboa/urls_api.py
requirements.txt
test_project/test_project/settings.py

First draft of a REST API.

---

doc/getting_started/install.rst
doc/index.rst

Hello,
I finally made very few changes on the doc to add information about plugins. Each one having its own doc, I only linked to the index page which contains the list of them.
Ref #776

Plugins doc

---

.travis.yml
modoboa/admin/tests/api.py
test_project/test_project/settings.py
tests.py

work in progress. need a PR to run travis

run tests with mysql

---

doc/extending/events.rst
modoboa/admin/forms/account.py
modoboa/admin/forms/domain.py
modoboa/admin/tests/test_account.py
modoboa/admin/views/alias.py
modoboa/admin/views/domain.py
modoboa/core/apps.py
modoboa/core/signals.py
modoboa/lib/middleware.py
modoboa/lib/signals.py
modoboa/limits/apps.py
modoboa/limits/constants.py
modoboa/limits/controls.py
modoboa/limits/forms.py
modoboa/limits/general_callbacks.py
modoboa/limits/handlers.py
modoboa/limits/lib.py
modoboa/limits/migrations/0003_auto_20160413_1046.py
modoboa/limits/migrations/0004_auto_20160413_1312.py
modoboa/limits/models.py
modoboa/limits/tests.py
modoboa/limits/urls.py
modoboa/limits/utils.py
modoboa/relaydomains/tests.py

Don't store current values in database, this is really not useful and it makes the code too complex too understand.
TODO:

Refactor: Limits

---

modoboa/core/commands/deploy.py
modoboa/core/management/commands/load_initial_data.py
modoboa/core/tests.py
tests.py

Possibility to change default username for initial admin.

---

modoboa/admin/tests/test_mapfiles.py
modoboa/core/management/commands/generate_postfix_maps.py
modoboa/core/utils.py

File credentials are preserved, only query is updated.
see #488

Upgrade mode.

---

doc/getting_started/upgrade.rst

Fixing Cronjob Documentation for 1.6.0

---

doc/getting_started/upgrade.rst

Update upgrade.rst - Typo fix:

---

modoboa/admin/constants.py
modoboa/admin/management/commands/subcommands/_mx.py

Remove deprecated provider and full DNS names.

---

modoboa/admin/tests/test_account.py
modoboa/core/models.py

Make sure to set the owner.

---

modoboa/admin/tests/test_mapfiles.py
modoboa/core/management/commands/generate_postfix_maps.py

Maps generation fixed for sqlite.

---

doc/upgrade.rst

Extensions won't work if they aren't upgraded as well.

Add doc on 1.6.0 upgrade and its breaking changes

---

modoboa/admin/forms/forward.py
modoboa/admin/models/alias.py
modoboa/admin/tests/test_user.py
modoboa/admin/views/user.py

Allow local addresses for forward definition.

---

modoboa/admin/forms/domain.py
modoboa/admin/tests/test_domain.py
modoboa/core/app_settings.py
modoboa/core/management/commands/load_initial_data.py
modoboa/core/tests/test_views.py

Possibility to change default password.

---

.travis.yml
doc/configuration.rst
doc/upgrade.rst
modoboa/admin/tests/test_account.py
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/tests/test_authentication.py
modoboa/core/tests/test_core.py
modoboa/core/tests/test_ldap.py
modoboa/lib/authbackends.py
test-requirements.txt
test_project/test_project/settings.py

SMTP authentication backend.

---

modoboa/core/app_settings.py
modoboa/core/extensions.py
modoboa/core/tests/test_extensions.py
modoboa/core/views/auth.py
modoboa/core/views/base.py

Fixed top redirection.

---

doc/manual_installation/dovecot.rst

Fixed queries.

---

modoboa/admin/forms/domain.py
modoboa/limits/models.py
modoboa/limits/tests/test_api.py
modoboa/limits/tests/test_import.py
modoboa/limits/tests/test_user_limits.py
modoboa/relaydomains/tests.py

Check that resellers can't define unlimited quota.

---

modoboa/admin/forms/domain.py
modoboa/admin/models/domain.py
modoboa/admin/serializers.py
modoboa/admin/tests/test_api.py
modoboa/admin/tests/test_domain.py
modoboa/admin/tests/test_import_.py

Default mailbox quota should not be greater than quota.

---

modoboa/admin/management/commands/subcommands/_repair.py

Repair everything (almost)
It doesn't works
It works

some moar fixes (unwanted autoreplies recipients / missing aliases)

---

modoboa/admin/management/commands/subcommands/_repair.py
modoboa/admin/tests/test_repair.py

postfix_autoreply know problems will be moved to the appropriate repository.

Do not include extensions code from core.

---

modoboa/lib/middleware.py

Use local thread storage.

---

modoboa/lib/middleware.py
modoboa/lib/signals.py

Make sure signal is not shared between threads.

---

doc/contributing/quota_res

Notes about quota changes and Reseller user in v1.7.0.

Notes about quota changes and Reseller user

---

modoboa/lib/middleware.py
modoboa/lib/signals.py

This is a temp. fix, the code using get_request() needs a rewrite...

Make sure request is local to current thread.

---

modoboa/core/management/commands/load_initial_data.py
modoboa/core/tests/test_core.py

Do not check default value.

---

requirements.txt

Bumped gevent to 1.2.1.

---

modoboa/core/factories.py
modoboa/core/management/commands/cleanlogs.py
modoboa/core/tests/test_core.py

Fixed cleanlogs command.

---

modoboa/core/app_settings.py
modoboa/core/tests/test_views.py
modoboa/core/views/dashboard.py

Custom news for resellers and domain admins.

---

modoboa/admin/tests/test_api.py
modoboa/core/extensions.py
modoboa/core/tests/stupid_extension_2/urls.py
modoboa/core/tests/stupid_extension_2/views.py
modoboa/core/tests/test_extensions.py
modoboa/limits/tests/test_api.py
modoboa/urls.py
modoboa/urls_api.py

Include plugins API urls if available.

---

modoboa/admin/models/alias.py
modoboa/admin/models/domain.py
modoboa/admin/models/domain_alias.py
modoboa/core/models.py
modoboa/relaydomains/models.py

Allowed more values.

---

modoboa/lib/authbackends.py

Moved import statement.

---

modoboa/admin/handlers.py
modoboa/admin/tests/test_import_.py
modoboa/core/models.py

Force lower-case addresses.

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py
modoboa/admin/tests/test_alias.py

Security fixes.

---

modoboa/limits/forms.py
modoboa/limits/lib.py
modoboa/limits/serializers.py
modoboa/limits/tests/test_api.py
modoboa/limits/urls_api.py
modoboa/limits/viewsets.py
modoboa/urls_api.py

New resources endpoints.

---

modoboa/core/views/dashboard.py

Catch requests exceptions.

---

modoboa/core/models.py
modoboa/lib/email_utils.py

Quote sender local-part.

---

modoboa/core/app_settings.py
modoboa/core/tests/test_views.py
modoboa/core/views/dashboard.py

Added setting to control widget visibility.

---

MANIFEST.in
modoboa/core/tests/test_authentication.py
modoboa/lib/tests.py

skip SMTP tests when needed

---

modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/tests/test_mx.py

Fixed notifications.

---

modoboa/admin/forms/domain.py
modoboa/admin/static/admin/js/admin.js
modoboa/admin/templates/admin/domain_options_form.html
modoboa/admin/tests/test_domain.py
modoboa/limits/tests/test_user_limits.py

Added new option to control mailbox creation.

---

doc/manual_installation/modoboa.rst

At this very point you are not yet inside a virtualenv.

Remove maybe missleading prefix

---

README.rst

This should fix #1141 /at least it does for me).

Add hint to demo installation to global README

---

ldap-requirements.txt
modoboa/lib/authbackends.py

Fixed custom authentication backend.

---

modoboa/admin/forms/account.py
modoboa/admin/serializers.py
modoboa/core/app_settings.py
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/forms.py
modoboa/core/password_validation.py
requirements.txt
test_project/test_project/settings.py

Replaced django-passwords by django's builtins.

---

modoboa/admin/models/alias.py
modoboa/admin/tests/test_import_.py

Fixed forward creation from import.

---

modoboa/core/forms.py
modoboa/core/tests/test_authentication.py
modoboa/core/views/__init__.py
modoboa/core/views/auth.py
modoboa/static/css/login.css
modoboa/static/css/offline.css
modoboa/templates/registration/base.html
modoboa/templates/registration/login.html
modoboa/templates/registration/password_reset_complete.html
modoboa/templates/registration/password_reset_confirm.html
modoboa/templates/registration/password_reset_done.html
modoboa/templates/registration/password_reset_email.html
modoboa/templates/registration/password_reset_form.html
modoboa/templates/registration/password_reset_subject.txt
modoboa/urls.py

Added password reset service.

---

modoboa/admin/models/domain.py
modoboa/admin/models/mailbox.py
modoboa/admin/templates/admin/domain_detail.html
modoboa/admin/tests/test_account.py
modoboa/admin/views/domain.py

Improved domain quota display.

---

modoboa/admin/serializers.py
modoboa/admin/tests/test_api.py

[admin] fixed account update API endpoint.

---

modoboa/admin/api.py
modoboa/admin/tests/test_api.py

[admin] fixed retrieve account endpoint.

---

modoboa/core/tests/test_authentication.py
modoboa/core/views/base.py

core: fixed open redirect security issue.

---

modoboa/admin/tests/test_domain.py
modoboa/admin/views/domain.py

admin: fixed zero division error with domain quota.

---

modoboa/core/forms.py
modoboa/core/tests/test_core.py

Fixed profile update view.

---

modoboa/admin/models/mailbox.py
modoboa/admin/tests/test_domain.py

admin: fixed domain quota display when db not ready.

---

modoboa/admin/forms/account.py
modoboa/admin/templates/admin/account_profile_form.html
modoboa/admin/tests/test_account.py
modoboa/admin/tests/test_alias.py
modoboa/admin/tests/test_mailbox_operations.py
modoboa/admin/views/identity.py
modoboa/limits/tests/test_domain_limits.py
modoboa/limits/tests/test_user_limits.py

admin: added profile form to account update view.

---

.travis.yml
modoboa/core/commands/deploy.py

core: include extension settings in every case.

---

modoboa/admin/tests/test_export.py
modoboa/core/models.py

Convert to bytes.

---

doc/manual_installation/dovecot.rst
modoboa/admin/handlers.py
modoboa/core/app_settings.py
modoboa/core/handlers.py
modoboa/core/management/commands/clean_inactive_accounts.py
modoboa/core/tests/test_core.py
modoboa/core/tests/test_views.py
modoboa/lib/permissions.py

core: Added management command to clean inactive accounts.

---

modoboa/admin/api.py
modoboa/admin/tests/test_api.py

Added search filter to account list service.

---

modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/tests/test_mx.py

Fixed domain admin queryset.

---

modoboa/admin/app_settings.py
modoboa/admin/forms/domain.py
modoboa/admin/lib.py
modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/models/__init__.py
modoboa/admin/models/domain.py
modoboa/admin/models/mxrecord.py
modoboa/admin/serializers.py
modoboa/admin/tests/test_api.py
modoboa/admin/tests/test_domain.py
modoboa/admin/tests/test_import_.py
modoboa/admin/tests/utils.py
modoboa/core/tests/test_views.py

Check MX validity when adding new domain.

---

doc/upgrade.rst
modoboa/core/commands/templates/settings.py.tpl

Fixed BASE_DIR value.

---

modoboa/admin/tests/test_account.py
modoboa/core/tests/test_authentication.py
modoboa/lib/cryptutils.py

Fixed password encryption with non-ascii chars.

---

modoboa/admin/forms/account.py
modoboa/admin/forms/domain.py
modoboa/admin/lib.py
modoboa/admin/serializers.py
modoboa/admin/static/admin/js/admin.js
modoboa/admin/templates/admin/account_general_form.html
modoboa/admin/templates/admin/domain_options_form.html
modoboa/admin/tests/test_account.py
modoboa/admin/tests/test_api.py
modoboa/admin/tests/test_domain.py
modoboa/core/app_settings.py
modoboa/core/tests/test_views.py

Added random password generator.

---

modoboa/admin/forms/account.py
modoboa/admin/models/mailbox.py
modoboa/limits/tests/test_user_limits.py

Fixed quota error.

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py

Fixed validation errors display.

---

modoboa/admin/app_settings.py
modoboa/admin/forms/account.py
modoboa/admin/handlers.py
modoboa/admin/static/admin/js/admin.js
modoboa/admin/templates/admin/index.html
modoboa/admin/templates/admin/mailform.html
modoboa/admin/tests/test_account.py
modoboa/core/tests/test_views.py
modoboa/static/js/autocompleter.js

Added new option to create an alias on mailbox rename.

---

modoboa/admin/templates/admin/domain_detail.html
modoboa/admin/templates/admin/domains_quota_headers.html
modoboa/admin/tests/test_domain.py
modoboa/admin/views/domain.py

Added sorting filters to quota list.

---

modoboa/admin/tests/test_domain.py
modoboa/admin/views/domain.py

Filter queryset.

---

modoboa/admin/management/commands/subcommands/_mx.py

Fixed py3 compat.

---

modoboa/locale/nl_NL/LC_MESSAGES/django.po

Description of the issue/feature this PR addresses: some dutch translations where missing or faulty

updated some dutch translations

---

modoboa/limits/locale/nl_NL/LC_MESSAGES/django.po

fixed translation

---

modoboa/relaydomains/locale/nl_NL/LC_MESSAGES/djangojs.po

translations fixed

---

modoboa/admin/locale/fr/LC_MESSAGES/djangojs.po

Fix mistake in french translation

---

modoboa/admin/locale/el_GR/LC_MESSAGES/django.po
modoboa/admin/locale/el_GR/LC_MESSAGES/djangojs.po
modoboa/core/constants.py
modoboa/limits/locale/el_GR/LC_MESSAGES/django.po
modoboa/locale/el_GR/LC_MESSAGES/django.po
modoboa/locale/el_GR/LC_MESSAGES/djangojs.po
modoboa/relaydomains/locale/el_GR/LC_MESSAGES/django.po
modoboa/relaydomains/locale/el_GR/LC_MESSAGES/djangojs.po

Added greek translation.

---

modoboa/admin/locale/pl_PL/LC_MESSAGES/django.po
modoboa/admin/locale/pl_PL/LC_MESSAGES/djangojs.po
modoboa/core/constants.py
modoboa/limits/locale/pl_PL/LC_MESSAGES/django.po
modoboa/locale/pl_PL/LC_MESSAGES/django.po
modoboa/locale/pl_PL/LC_MESSAGES/djangojs.po
modoboa/relaydomains/locale/pl_PL/LC_MESSAGES/django.po
modoboa/relaydomains/locale/pl_PL/LC_MESSAGES/djangojs.po
modoboa/transport/locale/pl_PL/LC_MESSAGES/django.po
modoboa/transport/locale/pl_PL/LC_MESSAGES/djangojs.po

Added polish translation.

---

modoboa/lib/email_utils.py
modoboa/lib/tests.py
modoboa/lib/u2u_decode.py

Fixed mailsploit vulnerability.

---

modoboa/lib/email_utils.py

Testing code that shouldn't have been included with modoboa/modoboa#1330, it breaks modoboa/modoboa-amavis#80

remove unrequired assert

---

modoboa/lib/email_utils.py
modoboa/lib/tests/test_email_utils.py

prevents new messages from being composed in webmail

getaddresses() expects a list

---

modoboa/lib/email_utils.py
modoboa/lib/tests/sample_messages/multipart-output-html_links.txt
modoboa/lib/tests/sample_messages/multipart-output-html_nolinks.txt
requirements.txt

with modoboa/modoboa-amavis#99 it fixes modoboa/modoboa-amavis#94

email utils error handling

---

modoboa/admin/forms/account.py
modoboa/admin/serializers.py
modoboa/admin/tests/test_account.py
modoboa/admin/tests/test_api.py
modoboa/core/handlers.py
modoboa/core/management/commands/communicate_with_public_api.py
modoboa/core/models.py
modoboa/lib/api_client.py
modoboa/lib/authbackends.py

Use default language code for new accounts.

---

doc/configuration.rst

Improve documentation for issue #1359

Add authentication log information in documentation

---

modoboa/static/js/global.js
modoboa/static/js/twocols_nav.js

Fixed error display in parameters form.

---

modoboa/admin/static/admin/js/admin.js
modoboa/admin/templates/admin/domains.html
modoboa/admin/tests/test_domain.py
modoboa/admin/urls.py
modoboa/admin/views/domain.py

Load next page of the right type.

---

modoboa/admin/models/domain.py

TXT records longer than 255 characters need split into chunks
fixes #1420

#1420 fix DKIM bind record

---

modoboa/lib/ldap_utils.py

[python-ldap](https://www.python-ldap.org/) 3.0 now raises a warning if unicode parameters are passed when [`bytes_mode = True`](https://www.python-ldap.org/en/latest/bytes_mode.html#the-bytes-mode), if not specified Python 2 defaults to `bytes mode = True`.
This PR ensures parameters are passed as str (bytes) on Python 2 and str (unicode) on Python 3.
I've set `bytes_mode` to `True` on Py2 to maintain compatability with django-auth-ldap which doesn't set bytes mode (so defaults to bytes on Py2).

fix python-ldap warnings on Python 2

---

modoboa/admin/tests/test_data/import_domains_iso8859.csv
modoboa/admin/tests/test_import_.py

Added unit test to cover import of non utf8 files.

---

.gitignore
.travis.yml
test-requirements.txt
tox.ini

tox -e server try to install MySQL and PosgreSQL for standard test (that use SQLite)

Fix tox serve command

---

modoboa/admin/api.py

Fixed documentation.

---

modoboa/admin/views/identity.py

Filter on tag label, not on dict.

---

modoboa/admin/management/commands/subcommands/_export.py
modoboa/admin/tests/test_export.py

Fixed python2 compat.

---

modoboa/relaydomains/forms.py

Disconnect signals since they have already been called.

---

modoboa/admin/api.py
modoboa/admin/serializers.py
modoboa/admin/templates/admin/domain_detail.html
modoboa/admin/tests/test_api.py

Added button to refresh (regenerate) a DKIM key.

---

modoboa/admin/api.py
modoboa/admin/models/mailbox.py
modoboa/admin/serializers.py
modoboa/admin/tests/test_api.py

Fixed PATCH method for account viewset.

---

modoboa/core/templatetags/core_tags.py

Display only one line per user.

---

modoboa/lib/email_utils.py

Fixed issues with email decoding.

---

modoboa/admin/forms/account.py
modoboa/admin/forms/domain.py
modoboa/admin/models/alias.py
modoboa/admin/models/domain.py
modoboa/admin/models/domain_alias.py
modoboa/admin/serializers.py
modoboa/admin/templates/admin/_domain_dnschecks_status.html
modoboa/admin/templates/admin/domain_detail.html
modoboa/test_settings.py

fixed: force lower case domain names and addresses.

---

modoboa/lib/email_utils.py

fixed: enhanced decoding for SMTPUTF8 support.

---

modoboa/admin/forms/account.py
modoboa/admin/forms/domain.py
modoboa/admin/locale/cs_CZ/LC_MESSAGES/django.po
modoboa/admin/locale/de/LC_MESSAGES/django.po
modoboa/admin/locale/el_GR/LC_MESSAGES/django.po
modoboa/admin/locale/en/LC_MESSAGES/django.po
modoboa/admin/locale/es/LC_MESSAGES/django.po
modoboa/admin/locale/fr/LC_MESSAGES/django.po
modoboa/admin/locale/it/LC_MESSAGES/django.po
modoboa/admin/locale/ja_JP/LC_MESSAGES/django.po
modoboa/admin/locale/nl_NL/LC_MESSAGES/django.po
modoboa/admin/locale/pl_PL/LC_MESSAGES/django.po
modoboa/admin/locale/pt_BR/LC_MESSAGES/django.po
modoboa/admin/locale/pt_PT/LC_MESSAGES/django.po
modoboa/admin/locale/ro_RO/LC_MESSAGES/django.po
modoboa/admin/locale/ru/LC_MESSAGES/django.po
modoboa/admin/locale/sv/LC_MESSAGES/django.po
modoboa/admin/locale/zh_TW/LC_MESSAGES/django.po
modoboa/admin/models/domain.py
modoboa/admin/serializers.py
modoboa/admin/templates/admin/domain_general_form.html
modoboa/admin/templates/admin/mailform.html
modoboa/lib/tests/test_web_utils.py
modoboa/lib/web_utils.py

Added support for unit when defining a quota.

---

modoboa/admin/lib.py
modoboa/admin/tests/test_mx.py
modoboa/admin/tests/utils.py

A or AAAA record might not be available.

---

modoboa/admin/forms/domain.py
modoboa/admin/models/domain.py
modoboa/admin/templates/admin/_domain_dnschecks_status.html
modoboa/admin/templates/admin/domain_detail.html
modoboa/dnstools/locale/en/LC_MESSAGES/django.po
modoboa/dnstools/locale/fr/LC_MESSAGES/django.po
modoboa/dnstools/templates/dnstools/domain_dns_configuration.html
modoboa/dnstools/tests.py
modoboa/dnstools/urls.py
modoboa/dnstools/views.py

Added DNS configuration page for domain.

---

modoboa/core/models.py

Display fullname when last_name is set too.

---

doc/configuration.rst

Fix simple typo: detailled -> detailed

---

modoboa/dnstools/lib.py
modoboa/dnstools/tests.py

Fix #1766 for all the RR types and with tests.

Handle multiple strings in DNS record value

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py
modoboa/admin/views/identity.py
modoboa/core/models.py
modoboa/limits/tests/test_user_limits.py

Remove domain permissions when role is SimpleUsers.

---

doc/configuration.rst
modoboa/core/app_settings.py
modoboa/core/tests/test_views.py
modoboa/ldapsync/lib.py
modoboa/lib/authbackends.py

Added support for a secondary LDAP server.

---

modoboa/core/app_settings.py

Retrieve LDAP groups with AD.

---

modoboa/core/app_settings.py
modoboa/core/tests/test_views.py
modoboa/ldapsync/lib.py
modoboa/ldapsync/management/commands/import_from_ldap_directory.py
modoboa/ldapsync/tests.py
test_data/base.ldif

New management command to import LDAP accounts.

---

modoboa/admin/tests/test_alias.py
modoboa/core/app_settings.py
modoboa/core/commands/deploy.py
modoboa/core/constants.py
modoboa/core/templates/core/api_access.html
modoboa/core/templates/core/user_profile.html
modoboa/core/tests/test_core.py
modoboa/core/views/user.py
modoboa/urls.py

Added setting to define external password url.

---

modoboa/admin/forms/__init__.py
modoboa/admin/forms/export.py
modoboa/admin/views/export.py
requirements.txt

Removed deprecated dependancy.

---

modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/migrations/0017_alarm.py
modoboa/admin/models/alarm.py
modoboa/admin/tests/test_mx.py
modoboa/admin/tests/utils.py
modoboa/policyd/core.py
requirements.txt

Improved notifications management in MX checks.

---

requirements.txt

Bumped passlib to 1.7.3

---

modoboa/admin/tests/test_user.py
modoboa/admin/views/user.py

Make sure to disable/enable self alias according to forward settings.

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py

Disable forward when account is disabled.

---

requirements.txt

Update Gevent and Greenlet version together

---

doc/manual_installation/modoboa.rst

Update the connection string for beginners

---

.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/config.yml

Update the Issue template and add config.yml with link to Discussions

Update Issue Template and links

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py

Disable internal alias too with the account

---

doc/contributing/getting_started.rst

Added a helpful description to new developers stuck.

Add some helpful tips to new developers

---

modoboa/admin/forms/account.py
modoboa/admin/models/alias.py
modoboa/admin/tests/test_account.py

The same than #2400 toward branch 1.x

Fix account alias 1 x

---

modoboa/admin/api/v2/serializers.py
modoboa/admin/app_settings.py
modoboa/core/api/v2/views.py
modoboa/parameters/api/v2/tests.py

Valid MXs field must contain only IPs.

---

modoboa/admin/handlers.py
modoboa/admin/tests/test_account.py

Make sure internal alias is disabled if account is disabled at creation

---

frontend/src/api/alarms.js
frontend/src/components/alarms/AlarmList.vue
frontend/src/components/domains/DomainList.vue
frontend/src/components/layout/Navbar.vue
frontend/src/router/index.js
frontend/src/views/alarms/Alarms.vue
modoboa/admin/api/v2/serializers.py
modoboa/admin/api/v2/tests.py
modoboa/admin/api/v2/urls.py
modoboa/admin/api/v2/viewsets.py
modoboa/admin/models/domain.py
modoboa/limits/models.py

Added new page to display opened alarms in UI v2.

---

README.rst

Minor grammatical changes

---

modoboa/admin/app_settings.py

Fix autoconfig check written as SPF check on new admin

---

frontend/src/components/layout/Navbar.vue

Fix bug introduced with #2517, with alarms added, settings index is increased by one :)

fixed settings' index

---

frontend/src/components/domains/DKIMKeyViewer.vue

Fixed domainkey entry

---

modoboa/admin/views/domain.py

Enforce POST methods for delete domain view.

---

modoboa/admin/views/identity.py

Enforce POST method for account delete view

---

modoboa/admin/tests/test_alias.py
modoboa/admin/views/alias.py
modoboa/limits/tests/test_user_limits.py

Ensure DELETE method for delete alias view

---

modoboa/core/commands/templates/settings.py.tpl
modoboa/maillog/management/commands/logparser.py
modoboa/maillog/tests/test_views.py
test_project/test_project/settings.py

Added locking mechanism to logparser command

---

modoboa/admin/models/domain.py
modoboa/admin/models/mailbox.py
modoboa/admin/tests/test_import_.py

Improved error messages

---

modoboa/core/forms.py
modoboa/core/tests/test_core.py

Prevent user from changing their password without the current one.

---

modoboa/core/api/v2/tests.py
modoboa/core/api/v2/views.py

Log connection error on api v2 to let fail2ban detect the attempt.

log message on failed auth on api v2

---

frontend/locale/fi/LC_MESSAGES/app.po
modoboa/admin/locale/fi/LC_MESSAGES/django.po
modoboa/admin/locale/fi/LC_MESSAGES/djangojs.po
modoboa/dnstools/locale/fi/LC_MESSAGES/django.po
modoboa/ldapsync/locale/fi/LC_MESSAGES/django.po
modoboa/limits/locale/fi/LC_MESSAGES/django.po
modoboa/locale/fi/LC_MESSAGES/django.po
modoboa/locale/fi/LC_MESSAGES/djangojs.po
modoboa/maillog/locale/fi/LC_MESSAGES/django.po
modoboa/maillog/locale/fi/LC_MESSAGES/djangojs.po
modoboa/policyd/locale/fi/LC_MESSAGES/django.po
modoboa/relaydomains/locale/fi/LC_MESSAGES/django.po
modoboa/relaydomains/locale/fi/LC_MESSAGES/djangojs.po
modoboa/transport/locale/fi/LC_MESSAGES/django.po
modoboa/transport/locale/fi/LC_MESSAGES/djangojs.po

* Description of the issue/feature this PR addresses:
Created Finnish language translations.
* Current behavior before PR:
Finnish language translation did not exist.
* Desired behavior after PR is merged:
Finnish language translation is available.

[IMP] Finnish translations

---

.github/workflows/modoboa.yml
modoboa/version.py

Check that the trigger is a tag to set custom version

better job handling

---

frontend/src/components/alarms/AlarmList.vue
modoboa/admin/api/v2/tests.py
modoboa/admin/api/v2/viewsets.py
modoboa/lib/pagination.py

Fixed pagination issue.

---

modoboa/admin/views/domain.py
modoboa/admin/views/identity.py

Added GET as allowed methods.

---

doc/upgrade.rst

Fixed upgrade instructions. Reported in #2997.

Fixed upgrade instructions

---

frontend/src/App.vue
frontend/src/api/repository.js
frontend/src/components/layout/Navbar.vue
frontend/src/components/parameters/ParametersForm.vue
frontend/src/views/TwoFA.vue

- Fixed alarmChecker 
- Reduced error on console when user is logging in/out
- Fixed parameters tabs red indicator not resetting on menu switching

Multiple frontend fix

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py

Only create not internal aliases from account form

---

frontend/src/components/identities/AccountCreationForm.vue
frontend/src/components/identities/AccountGeneralForm.vue
frontend/src/components/identities/AccountPasswordForm.vue
frontend/src/mixins/importExport.js

Fixed creation of superadmin with new UI

---

doc/installation.rst
doc/upgrade.rst

doc improvement

---

modoboa/admin/api/v2/serializers.py
modoboa/admin/app_settings.py
modoboa/admin/lib.py
modoboa/admin/tests/test_mx.py
modoboa/admin/tests/utils.py
modoboa/core/tests/test_views.py
modoboa/dnstools/lib.py

Added option to disable IPV6 mx checks

---

modoboa/admin/api/v1/serializers.py
modoboa/admin/api/v1/tests.py
modoboa/admin/api/v2/tests.py
modoboa/admin/models/alias.py

Prevent creation of same alias addresses using different case

---

modoboa/core/models.py
requirements.txt

Prevent parameters loading at this time

---

doc/upgrade.rst
modoboa/admin/constants.py

Removed SORBS dnsbl

---

doc/rest_api.rst

Removed old api doc links and clarify API v2 doc access

---

modoboa/admin/api/v2/serializers.py
modoboa/admin/api/v2/tests.py

Prevent too long usernames (RFC5321)

---

README.rst
modoboa/admin/api/v2/serializers.py
modoboa/admin/constants.py
modoboa/admin/management/commands/subcommands/_manage_dkim_keys.py
modoboa/parameters/api/v2/tests.py

Removed serializer check for dkim dir, added alarms on gen

---

modoboa/admin/lib.py

Description of the issue/feature this PR addresses: see #3165

use authoritative server to perform dns checks

---

CHANGELOG.md

Update CHANGELOG.md - Typo -> Postfix

---

modoboa/admin/handlers.py
modoboa/core/signals.py
modoboa/core/tests/test_authentication.py
modoboa/core/views/auth.py

Propagate password to final session.

---

.github/workflows/modoboa.yml
docker/Dockerfile.dev
modoboa/core/checks.py
modoboa/core/models.py
modoboa/core/password_hashers/__init__.py
modoboa/core/password_hashers/base.py
modoboa/core/tests/test_authentication.py
modoboa/core/tests/test_checks.py
modoboa/lib/email_utils.py
modoboa/lib/tests/__init__.py
modoboa/lib/tests/sample_messages/multipart-input.txt
modoboa/lib/tests/sample_messages/multipart-output-html_links.txt
modoboa/lib/tests/sample_messages/multipart-output-html_nolinks.txt
modoboa/lib/tests/sample_messages/multipart-output-plain_nolinks.txt
modoboa/lib/tests/test_email_utils.py
requirements.txt

Dropped support for Python 3.8
Added support for Python 3.12

Updated test matrix

---

doc/upgrade.rst
modoboa/core/commands/templates/settings.py.tpl

Ignore warning for now (until we find a replacement).

---

frontend/src/api/admin.js
frontend/src/layouts/dashboard/NavBar.vue
frontend/src/stores/global.store.js
frontend/src/stores/index.js
frontend/src/views/admin/InformationView.vue
frontend/src/views/admin/ParametersView.vue
modoboa/core/api/v2/serializers.py
modoboa/core/api/v2/urls.py
modoboa/core/api/v2/views.py
modoboa/core/checks.py
modoboa/core/handlers.py
modoboa/core/models.py
modoboa/core/password_hashers/__init__.py
modoboa/core/templates/core/information.html
modoboa/core/views/admin.py
modoboa/parameters/tools.py
modoboa/templates/common/top_notifications.html

Also display notifications in new admin.
see #3350

Deal with password scheme deprecation (crypt as of now)

---

docker/Dockerfile.dev
frontend/src/router/index.js
frontend/src/stores/auth.store.js
frontend/src/views/login/LoginCallbackView.vue
frontend/src/views/login/LoginView.vue

Note : 
- I had to force alpine version to 3.20, 3.21 wouldn't let me build the docker image (GCC error on rrdtool compiling).
- authStore.validateAccess() is now awaited, so the router knows whether the user needs to be redirected to the login page or not. I couldn't check the impact on loading time (should be next to null)...

Display text when login on new-admin

---

docker/dovecot_config/auth-custom.conf
frontend/src/api/repository.js
frontend/src/views/account/FiltersView.vue
modoboa/core/checks.py
modoboa/sievefilters/api/v2/tests.py
modoboa/sievefilters/api/v2/viewsets.py
modoboa/sievefilters/lib.py
modoboa/sievefilters/mocks.py

And fixed the display of a null value when no filterset are active.
also fix on migration when using sqlite

Use raw mode on custom or broken sieve file

---

frontend/src/api/capabilities.js
frontend/src/layouts/admin/AdminLayout.vue
modoboa/core/api/v2/tests.py
modoboa/core/api/v2/urls.py
modoboa/core/api/v2/views.py
modoboa/core/utils.py
modoboa/parameters/api/v2/tests.py
modoboa/rspamd/__init__.py
modoboa/rspamd/admin.py
modoboa/rspamd/api/v2/serializers.py
modoboa/rspamd/app_settings.py
modoboa/rspamd/apps.py
modoboa/rspamd/handlers.py
modoboa/rspamd/management/commands/manage_rspamd_maps.py
modoboa/rspamd/models.py
modoboa/rspamd/tests.py
modoboa/rspamd/utils.py
modoboa/rspamd/views.py
test_project/test_project/settings.py

@tonioo I've got [an issue with this](https://github.com/modoboa/modoboa/blob/bd2e5c76c3604392fc6bc9b472874e83283d7704/frontend/src/layouts/admin/AdminLayout.vue#L99). Any idea on how to make the js object reactive to a ref() ? Else I can drop the feature.

Import Rspamd to main repo

---

modoboa/__init__.py
modoboa/autoreply/models.py
modoboa/core/utils.py
modoboa/lib/api_client.py
modoboa/lib/email_utils.py
modoboa/webmail/lib/sendmail.py
pyproject.toml

Use importlib.metadata and packaging instead.

Replaced calls to pkg_resource.

---

frontend/src/api/accounts.js
frontend/src/components/admin/domains/DomainAdminList.vue
frontend/src/components/admin/domains/DomainEditForm.vue
frontend/src/components/admin/identities/AccountCreationForm.vue
frontend/src/components/admin/identities/AccountEditForm.vue
frontend/src/components/admin/identities/AccountSummary.vue
frontend/src/components/admin/identities/form_steps/AccountGeneralForm.vue
frontend/src/components/admin/identities/form_steps/AccountMailboxForm.vue
frontend/src/components/admin/identities/form_steps/AccountRoleForm.vue
frontend/src/components/shared/NavBar.vue
frontend/src/components/tools/ChoiceField.vue
frontend/src/components/tools/CreationForm.vue
frontend/src/components/tools/EmailField.vue
frontend/src/components/tools/ResourcesView.vue
frontend/src/composables/permissions.js
frontend/src/constants.json
frontend/src/layouts/admin/AdminLayout.vue
frontend/src/plugins/permissions.js
frontend/src/router/index.js
frontend/src/views/account/SettingsView.vue
frontend/src/views/admin/identities/AccountView.vue
modoboa/admin/api/v2/viewsets.py
modoboa/lib/permissions.py
modoboa/parameters/api/v2/viewsets.py

Various fixes about Reseller mode in frontend.

---

frontend/public/config.json
frontend/src/stores/auth.store.js

It will allows compatibility with multi hostname envs.

Build redirect uri dynamically when needed.

---

frontend/src/api/alarms.js
modoboa/admin/api/v2/serializers.py
modoboa/admin/api/v2/tests.py
modoboa/admin/api/v2/viewsets.py

Changed HTTP method for alarm bulk delete endpoint

---

doc/manual_installation/radicale.rst

Added extra steps for manual installation
Added set-up for using radicale with clients like TB
Added a link to radicale's doc to set-up a reverse proxy
Description of the issue/feature this PR addresses: just extra documentation info
Current behavior before PR: N/A
Desired behavior after PR is merged: N/A

Update radicale.rst with extra information

---

frontend/src/api/accounts.js
frontend/src/components/admin/identities/IdentityList.vue
modoboa/pdfcredentials/api/v2/serializers.py
modoboa/pdfcredentials/api/v2/tests.py
modoboa/pdfcredentials/app_settings.py

Make sure download link for PDF credentials actually work.

---

frontend/src/components/admin/domains/DomainSummary.vue
frontend/src/components/admin/domains/RelayDomainSummary.vue
frontend/src/components/tools/BooleanIcon.vue
frontend/src/views/admin/domains/DomainView.vue

Display transport settings for relay domains.

---

modoboa/core/api/v2/serializers.py
modoboa/core/app_settings.py
modoboa/core/management/commands/cleanlogs.py
modoboa/core/tests/test_core.py

Added cleanup process for message history.

---

frontend/src/components/admin/domains/DNSBLSummary.vue
frontend/src/components/admin/domains/DNSDetail.vue
modoboa/admin/models/mxrecord.py
modoboa/dnstools/api/v2/serializers.py

In domain detail page, display red bell when a MX is listed by one or more DNSBL providers.

Display domain DNSBL issues when necessary

---

frontend/src/components/shared/NavBar.vue
frontend/src/components/tools/CreationForm.vue
frontend/src/composables/logos.js
frontend/src/layouts/webmail/WebmailLayout.vue

Use custom logo also in webmail

---

frontend/src/components/webmail/EmailList.vue
modoboa/webmail/lib/imaputils.py

Added missing quotes to SORT parameter
