modoboa/modoboa

doc/extending/getting_started.rst

Fix #716 : append faq item about bower command missing

Fix #716 : append faq item about bower command missing

---

modoboa/core/commands/templates/settings.py.tpl
requirements.txt

Fix remote_addr if modoboa django app is powered by apache or nginx proxy

Fix remote_addr if modoboa django app is powered by apache or nginx proxy

---

modoboa/core/app_settings.py
modoboa/locale/cs_CZ/LC_MESSAGES/django.po
modoboa/locale/de/LC_MESSAGES/django.po
modoboa/locale/de/LC_MESSAGES/djangojs.po
modoboa/locale/en/LC_MESSAGES/django.po
modoboa/locale/es/LC_MESSAGES/django.po
modoboa/locale/fr/LC_MESSAGES/django.po
modoboa/locale/it/LC_MESSAGES/django.po
modoboa/locale/nl_NL/LC_MESSAGES/django.po
modoboa/locale/pt_BR/LC_MESSAGES/django.po
modoboa/locale/pt_PT/LC_MESSAGES/django.po
modoboa/locale/ru/LC_MESSAGES/django.po
modoboa/locale/sv/LC_MESSAGES/django.po

Fix typo in help text and all corresponding translations' msgids, also fix translation of that item in German and Dutch.
Revise German translation.

Fix typo, revise German translation

---

modoboa/core/models.py

Before this fix, role is always empty when AccountCreated event was executed (see https://github.com/modoboa/modoboa-admin-limits/pull/3 )

Before this fix, role is always empty when AccountCreated event was executed

---

modoboa/core/templates/core/settings_header.html

The path to settings.css seems to be invalid in settings_headers.html template.

Fix invalid path for settings.css

---

modoboa/core/commands/templates/settings.py.tpl

PR #794 inadvertently missed a comma that results in, when devmode is set, a dependency of 'authtokendjangobower' attempting to be installed.
This splits that into the two dependencies it was meant to be.

Correct INSTALLED_APPS in devmode

---

modoboa/admin/tests/password_schemes.py
modoboa/core/app_settings.py
modoboa/core/password_hashers/__init__.py
modoboa/core/password_hashers/advanced.py

based on tag 1.4.5. adds BCRYPTHasher to modoboa.core.password_hashers.advanced, along with necessary glue. This implementation fixes "rounds" at 12.

initial implementation of BCRYPTHasher with unit test

---

modoboa/admin/tests/test_alias.py

Steps to reproduce:
- Go to the Identities view
- Add 2 user accounts
- Add a distribution list with these 2 users set as recipients
- Click on user and hit the Update button
- Observe distribution list being deleted
These is a WIP. Test case is included.

Distribution lists deleted on related user update

---

doc/getting_started/upgrade.rst
modoboa/core/commands/templates/settings.py.tpl

Hi,
there is a typo in the swagger's module name - `.` instead of `_`.

Fix swagger app name in INSTALLED_APPS

---

.gitignore
modoboa/admin/tests/test_account.py
modoboa/core/tests.py
modoboa/lib/tests.py
modoboa/test_settings.py
test_project/test_project/settings.py
tox.ini

This allow to use tox locally with sqlite (no ldap/postgres/complex stuff). This may ease contributions!
The only thing missing is a few fixtures so you can login when using tox -e serve. Any idea how to do that ? I guess you already have some code for that at least for testing.

allow to use tox to run tests/serve locally in an easy way

---

modoboa/admin/handlers.py
modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/models/domain.py
modoboa/admin/templates/admin/domain_detail.html
modoboa/admin/templates/admin/domains_table.html
modoboa/admin/tests/test_mx.py

We also need to run ```management.call_command("modo", "check_mx", "--skip-admin-emails", "--domain=%s" % domain.id)``` when a domain is added. Any favourite way to do that ?

improve mx search

---

.travis.yml
modoboa/test_settings.py

Travis test create MySQL database when test PostgreSQL and vice versa
Lose 6s to install psycopg2 when testing MySQL
Improve speed, and remove the unnecessary library

Improve travis

---

modoboa/core/templates/core/dashboard.html

#1114
Dashboard has empty title tag
Dashboard has "Dashboard" title tag

Add title tag for dashboard

---

doc/index.rst

- modoboa-dmarc documentation link
- modoboa-imap-migration documentation link
- modoboa-pdfcredentials documentation link

Fixed documentation links on doc/index.rst file

---

doc/manual_installation/webserver.rst

This is needed to have the Authorization header passed to the API.
Took me a while to figure this out, so it would probably be good to document it.

docs: Mention WSGIPassAuthorization in Apache config

---

modoboa/core/views/base.py

When we logout, the new url has not the "next" get parameter. nextlocation is not None in this case, but "None" (the string). 
So if we re-login, we are redirected to accounts/login/None, that does not exists (404).
I add ' != "None" ' to the conditions, so now the re-login works.

Fix redirect url

---

modoboa/admin/models/domain.py
modoboa/core/models.py
modoboa/lib/form_utils.py

Python 3 doesn't interpret __unicode__ function, but use __str__ function instead.
So, for example, in DNSBL summary, instead of the domain name and IP in the second column, we have "MXRecord object"...
Restore the view of domain name and IP, like python2 version.
I also add a __str__ function beside every __unicode__ function. Note that python3 uses unicode by default, so I remove in str function the "u" prefix for strings.
The change in file modoboa/admin/models/domain.py fixes the problem described above. The other changes have not been tested by my. Please check they are correct.

Python3 compatibility: add __str__ functions in addition to __unicode__ function

---

doc/manual_installation/modoboa.rst

From pypi page:
---------------
mysqlclient is a fork of MySQL-python. It adds Python 3 support
and fixed many bugs.
...
MySQL-5.5 through 5.7 and Python 2.7, 3.4+ are currently supported.
**Description of the issue/feature this PR addresses:** Recommend a better supported MySQL connector.
**Current behavior before PR:** MySQL-python doesn't support Python 3 and hasn't been updated for years.
**Desired behavior after PR is merged:** To whoever install modoboa manually have pure joy! :joy:

Update manual installation doc to recommend mysqlclient

---

modoboa/admin/app_settings.py
modoboa/core/commands/deploy.py

1. Deploy assistant uses `eval(input(…))` when showing prompts
2. Deploy assistant invokes `manage.py` using `python`(2) instead of the current interpreter
ad (1): `UnboundLocalError`, all entries have to be quoted by the user or exceptions or worse may happen (and on Python 2 everything is `eval`'d twice!!)
ad (2): Deploy fails if system Python is Python 2, but one tries to deply Modoboa using Python 3
No more errors on deploy.

Solve issues with deploy assistant

---

doc/installation.rst

Update Installation Doc to fix missing python path error
Description of the issue/feature this PR addresses: Resolution of the modoboa installer not being able to find the appropriate python installed
Current behavior before PR: Installation breaks with the error '/usr/bin/env: ‘python’: No such file or directory'
Desired behavior after PR is merged: Installation runs smooth

Update Installation Doc

---

requirements.txt

I found a bug in the coreapi to create a domain
this problem is on the djangorestframework and fix ten days ago 
see: https://github.com/mozilla/mozillians/pull/1892
https://github.com/encode/django-rest-framework/issues/1101
Fix: https://github.com/encode/django-rest-framework/pull/5038/files

Impossible to enable domain on creation or update with coreapi

---

modoboa/lib/email_utils.py

Currently SQLemail ([modoboa-amavis](https://github.com/modoboa/modoboa-amavis/blob/master/modoboa_amavis/sql_email.py#L18)) does not escape html characters in plain text messages which can potentially allow harmful html to be displayed when viewing quarantined messages.
ImapEmail ([modoboa-webmail](https://github.com/modoboa/modoboa-webmail/blob/master/modoboa_webmail/lib/imapemail.py#L131)) overrides viewmail_plain() and escapes the message prior to calling Email.viewmail_plain(). This should be done in the Email() class as it's beneficial for all sub classes of Email and I can't think of an occasion when you wouldn't want to escape HTML when viewing a plain text message.
conditional_escape is used to prevent double escaping when called by ImapEmail.viewmail_plain().

escape html in plain text messages

---

modoboa/core/commands/deploy.py
modoboa/core/commands/templates/settings.py.tpl

Set ADMINS to a list of all the people who get code error notifications. When DEBUG=False Django emails these people the details of exceptions raised in the request/response cycle.
modoboa disables this by overriding `settings.LOGGING`, e5a05f2 restores this feature it's only enabled if `settings.ADMINS` is defined.
51566ce adds utf-8 support when generating `settings.py`, I might have accidentally thrown a utf-8 character into `settings.py.tpl` by accident (now removed) 😃

On error email admins

---

modoboa/lib/email_utils.py
modoboa/lib/tests/__init__.py
modoboa/lib/tests/sample_messages/multipart-input.txt
modoboa/lib/tests/sample_messages/multipart-output-html_links.txt
modoboa/lib/tests/sample_messages/multipart-output-html_nolinks.txt
modoboa/lib/tests/sample_messages/multipart-output-plain_nolinks.txt
modoboa/lib/tests/sample_messages/text_plain-input.txt
modoboa/lib/tests/sample_messages/text_plain-output-plain_nolinks.txt
modoboa/lib/tests/test_email_utils.py
modoboa/lib/tests/test_u2u_decode.py
requirements.txt

This is a refactor of `moboboa.lib.email_utils.Email`, currently it has some dead code (`__save_image`) and it has trouble parsing messages containing certain attachemnt types.
73bceee splits `modoboa/lib/tests.py` into separate files so that each file only tests one component. The code in `modoboa/lib/tests/__init__.py` is there so as not to break everything that imports `modoboa.lib.tests`
ce02d24 adds python 3 support for landscape.io and simplifies codecov ignore paths
c67f685 and e38cfb7 adds the improved `Email` class and tests.
**This PR depends on a similar PR for modoboa/modoboa-amavis#80 as it depends on moboboa.lib.email_utils.Email.**
modoboa-webmail isn't affected as it implements it's own parser to fetch e-mails from IMAP.

Improved email parser

---

doc/manual_installation/modoboa.rst

Documentation update to fix modoboa/modoboa-installer#136

MariaDB >= 10.2 requires mysqlclient >= 1.3.11

---

.travis.yml
codecov.yml
modoboa/test_settings.py
test-requirements.txt

Django automatically renames test databases to 'test_%s' % settings.DATABASES[*]["NAME"], so modoboa_test became test_modoboa_test. There's no point creating the database in `before script` as the test suite creates it.
https://docs.djangoproject.com/en/1.11/topics/testing/advanced/#django.db.connection.creation.create_test_db
- target oldest currently supported database servers, travis currently defaults to PostgreSQL 9.2 which isn't supported anymore.
- move database dependencies out of travis.yml into test_requirements.txt and pin to minimum versions recommended by django.
See https://docs.djangoproject.com/en/1.11/ref/databases/
- use MySQL root user for tests, we already use the root user (postgres) for PostgreSQL.
- fix typo in modoboa/test_settings for DB variable, default should …

 Fix test database setup

---

modoboa/admin/lib.py
modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/tests/test_api.py
modoboa/admin/tests/test_domain.py
modoboa/admin/tests/test_import_.py
modoboa/admin/tests/test_mx.py
modoboa/admin/tests/utils.py
test_project/test_project/settings.py

- add support for looking up IPv6 addresses (socket.getaddrinfo)
- add support for International Domain Names in case the DNS reponse contains one
- when looking up an ip address, don't stop on the first failure check all addresses
- add logging for potential configuration errors:
- DNS configuration errors (i.e. no MX records)
- server name resolution errors (i.e. resolv.conf doesn't contain a working name server)
- invalid values in MX records
- update mock results for tests

Add IPv6 support to mx checks

---

modoboa/admin/handlers.py
modoboa/admin/management/commands/subcommands/_export.py
modoboa/admin/management/commands/subcommands/_import.py
modoboa/admin/tests/test_import_.py
modoboa/admin/views/export.py
modoboa/admin/views/import_.py
modoboa/core/models.py
requirements.txt

The csv module on Python 2 doesn't support utf8 (even encoded as bytes), the easiest fix is to use the csv module backported from Python 3.
I've also replaced `fct = getattr(lib, "import_%s" % row[0].strip())` with a lookup dict `IMPORT_OBJECT_TYPES`. There's a potential here for somebody  to attempt to call other functions with a csv import file.
Fixes #1312
See https://docs.python.org/2/library/csv.html
See https://github.com/ryanhiebert/backports.csv

Fix importing csv files containing utf8 characters

---

doc/manual_installation/postfix.rst
doc/upgrade.rst

Fix instructions for a new installs, and upgrades to reflect recent changes.
- #1309 removed `sql-relaydomains-transport.cf`
- #1322 merged `sql-sender-login-*.cf` into `sql-sender-login-map.cf`
- remove duplicate `relay_domains`

fix postfix documentation

---

modoboa/admin/models/mailbox.py

**Description of the issue/feature this PR addresses:**
When `Handle mailboxes on filesystem` is enabled an internal error is raised accessing `Mailbox.mail_home`.
**Current behavior before PR:**
`doveadm user user@test.com -f home` returns
```
field   value
uid     1000
gid     1000
home    /home/vmail/test.com/user
mail    maildir:~/Maildir:LAYOUT=fs
quota_rule      *:bytes=500M
userdb lookup: user -f doesn't exist
userdb lookup: user home doesn't exist
```
**Desired behavior after PR is merged:**
Modoboa expects `doveadm user -f home user@test.com` to return
`/home/vmail/test.com/user`
Fixes #1267

fix order of doveadm paramters

---

modoboa/lib/cryptutils.py
modoboa/lib/tests/test_cryptutils.py

Cryptography can be a black art, rather than rolling our own crypto
functions use the ones provided by the Python Cryptography module.
- `encrypt()` and `decrypt()`
- ECB is insecure and the Python Cryptography module recommends[1]
against using it.  The Python Cryptography module offers Fernet[2]
for encrypting values using a secret_key.
- Djangos `settings.SECRET_KEY` exists for things like encrypting
passwords, use it instead of Modoboas own `secret_key`[3].
- `settings.SECRET_KEY` is truncated to 32 characters as Fernet requires
a key 32 characters long.
- `random_key()` uses Dangos get_random_string() method, the same
code used to generate settings.SECRET_KEY
- add tests for cryptutil methods
[1] https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=ecb#i …

refactor cryptutils

---

modoboa/lib/email_utils.py
modoboa/lib/tests/test_email_utils.py

I've kept `split_address()` and `split_local_part()` for the modoboa-amavis code to work.
Needed for modoboa/modoboa-amavis#89

improve e-mail address splitting functions

---

modoboa/core/templates/core/parameters.html

client side form validation currently fails if there's an error on a
tab that's not visible.
#1370
#1371

disable client side form validation (#1370)

---

modoboa/relaydomains/forms.py

it will also avoid the trigger of two post_save signals for the domain,
which can lead to unexpected issues.
see #1380

fix: do not save the domain if not necessary.

---

postgresql-requirements.txt
test-requirements.txt

also bump the minimum version to 2.7.4 as this is when the psycopg2-binary became available.
See #1417 and http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/

#1417 psycopg2 binary package has been renamed to psycopg2-binary

---

doc/manual_installation/webserver.rst

Current Debian stable ships with uWSGI 2.0.14 while the current upstream version to the date is only 2.0.17. The original warning no longer applies, there's no need to scare off Debian or Ubuntu users.

[docs] remove uwsgi warning

---

dev-requirements.txt
modoboa/core/commands/deploy.py
requirements.txt
setup.py
test-requirements.txt

remove dependency on pip internals

---

dev-requirements.txt
setup.py
test-requirements.txt

Adding external dependencies to `setup.py` was a bad idea, for now continue to use pip internal functions until a better solution can be found.

 revert #1439 changes

---

modoboa/admin/tests/test_api.py
modoboa/admin/tests/test_domain.py
modoboa/admin/tests/test_import_.py
modoboa/admin/tests/test_mailbox_operations.py
modoboa/admin/tests/test_mx.py
modoboa/core/tests/test_authentication.py
test-requirements.txt

In python >=3.3 mock is included in the Python standard library (`unittest.mock`).

prefer standard library version of mock over back port

---

modoboa/admin/management/commands/subcommands/_export.py
modoboa/admin/management/commands/subcommands/_import.py
modoboa/admin/tests/test_data/import_domains.csv
modoboa/admin/tests/test_data/import_domains_duplicates.csv
modoboa/admin/tests/test_import_.py
modoboa/admin/views/export.py
modoboa/admin/views/import_.py
requirements.txt

I can't replicate the issue in #1430, but here's a couple of changes  that might fix it.
- ensure command line args are unicode(py2)/str(py3)
- use io.open to open file with utf8 encoding
- set newlines="" in open commands, csv module takes care of line endings
- add tests for import command

fix import command

---

setup.py

fixes modoboa/modoboa-installer#197

PEP508 markers in requirements.txt have been broken since dfabe89

---

requirements.txt

Attaching an image to an e-mail in webmail causes an `Internal Server Error` because Pillow an optional dependency for ckeditor is missing.
As django-ckeditor is in modoboas `requirements.txt` I've included it here and not in modoboa-webmail.

add missing optional dependency used by ckeditor for attaching images

---

modoboa/core/commands/deploy.py
modoboa/core/management/commands/generate_postfix_maps.py

Won't be removed until Django 3 but might as well fix it as it's been an alias since Django 1.9.

postgresql_psycopg2 is now an alias for postgresql

---

doc/manual_installation/modoboa.rst

Docs for manual installation are missing the update_statistics call in crontab.
It has been added to the installer with [this commit](https://github.com/modoboa/modoboa-installer/commit/6c6945c11b8763851732041e3c2fbd4abda44107) so I guess it should be added here too.

Docs for manual installation: Added update_statistics call to cron.

---

modoboa/dnstools/lib.py

The DKIM key is base64 encoded, meaning it can end with "=" signs
Split on "=" and check if you have 2 'parts' (key and value) will fail in these cases.
By using split("=",1) we make sure we only slit on the first occurence of the "=" sign
(solves modoboa#1647 and partially modoboa#1640 and modoboa#1642)
DKIM checks fail
DKIM checks work

Bugfix: DKIM checks fail

---

modoboa/dnstools/lib.py
modoboa/dnstools/tests.py
mysql-requirements.txt

dnstools: ignore extra spaces in records.

---

modoboa/core/password_hashers/advanced.py

A regression introduces about year ago caused the rounds parameter to be ignored
The rounds parameter is ignore, passlib always uses the default which for sha512_crypt is 656000.
The rounds parameter is honored.
You can verify this by setting it to != 656000 and the password hash to sha{256,512}_crypt.
Then update the pw and verify the result in the `password` field of the `core_user` table

fix regression that caused the rounds parameter to be ignored

---

modoboa/core/password_hashers/__init__.py
modoboa/core/password_hashers/advanced.py
modoboa/core/password_hashers/base.py
modoboa/core/tests/test_authentication.py
modoboa/core/views/auth.py
requirements.txt

This PR implements support for the argon2 password hash and adds the ability to rehash passwords not only for schema changes but also for parameter changes. Right now the later is only implemented for argon2 hashes, but could also be interesting for sha{256,512}crypt hashes.
no argon2 support
working argon2 support with the ability to rehash password for parameter update on login
I have not (yet) written any documentation about the argon2 functionality. Because I'm unsure where it would fit best, any ideas?
#1673

Argon2 support

---

modoboa/admin/constants.py

Description of the issue/feature this PR addresses: Messages from the system about a domain being blacklisted at bad.psky.me when that is not correct, the provider is hijacked or is otherwise nonfunctional as of April 21.
Several messages a day to postmaster from Modoboa saying that a domain has been blacklisted at bad.psky.me.
No more messages from Modoboa about this blacklist provider as it is removed from checks.

Removed bad DNSBL bad.psky.me - see issue #1721.

---

.travis.yml
doc/configuration.rst
modoboa/core/app_settings.py
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/tests/test_views.py
modoboa/ldapsync/__init__.py
modoboa/ldapsync/apps.py
modoboa/ldapsync/handlers.py
modoboa/ldapsync/lib.py
modoboa/ldapsync/tests.py
test_project/test_project/settings.py

Synchronization of user accounts between Modoboa and an LDAP directory.

LDAP synchronization process

---

modoboa/core/password_hashers/advanced.py
modoboa/core/tests/test_authentication.py
requirements.txt
setup.py
test-requirements.txt

Thanks to #1690, Argon2 is now supported as password hasher. However, it is not optional and Argon2 requires a third-party library - that's why Django do not use it as default (see the [related documentation](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#using-argon2-with-django)). This PR try to make this password hasher optional.
* argon2 is in the requirements
* argon2 is imported in modoboa/core/password_hashers/advanced.py
* ARGON2IDHasher is defined and inherits from PasswordHasher
* tests depend on argon2
* argon2 is not in requirements but in extras
* argon2 is imported in modoboa/core/password_hashers/advanced.py with a `try...except` catch
* ARGON2IDHasher is defined but only inherits from PasswordHasher if argon2 is installed
* tests related to argon2 are skipped …

Make dependency on argon2 optional

---

doc/configuration.rst

Fixes ldapsync parameters table in docs/configuration.

doc: fix ldapsync parameters table.

---

modoboa/core/password_hashers/advanced.py

Fix exception handling in argon2 for mismatching passwords
When the argon2 hasher is used and the given password does not match the hash, an "internal error" occurs.
The proper "invalid username or password" message is shown and now redirect to the error page happens.

Fix exception handling in argon2 for mismatching passwords

---

modoboa/admin/forms/account.py
modoboa/admin/tests/test_account.py

In the account edition modal for a user with *DomainAdmins* role, removing a domain from its permissions is not considered when the form is submitted. The user is still an admin for the domain.

Fix account removal from domain admins

---

modoboa/core/management/commands/generate_postfix_maps.py
modoboa/ldapsync/tests.py
test_project/test_project/settings.py
tox.ini

This fixes some cases where we want that tox passes all tests locally and updates Python versions to check.

Update tox.ini and tests to be run locally

---

modoboa/core/management/commands/load_initial_data.py
modoboa/core/tests/stupid_extension_1/modo_extension.py
modoboa/core/tests/stupid_extension_2/modo_extension.py
modoboa/core/tests/test_extensions.py

While executing `load_initial_data` command, an exception raised by an extension is not handled. As a result, the user could have difficulties to know what happened but also the command stops and the data of the other extensions will not be loaded - except with PostgreSQL database where no data at all will be loaded.
An error is displayed to tell that the extension data could not be initialized, and the process continues.

Catch errors in load_initial_data command

---

modoboa/core/tests/test_ldap.py
modoboa/lib/authbackends.py

Allow login with username instead of email for LDAP.

---

.gitignore
modoboa/admin/postfix_maps.py

New functionality: account can send email from a domain with any address
Originally during the sending of email there is a check to not send out
email from an unaothorized address. There you can set only exact email
addresses.
With this modification you are able to send out any address within a
specified domain. This is the reverse methodology to the catchall
function, you can use this to catch everything and send everything in a
domain, usable for a project management/ERP software.
To enable this you need to set "@domain.com" as sender address alias
just like you set up a cacthall functionality.

New functionality: account can send email from a domain with any address

---

modoboa/core/commands/templates/settings.py.tpl
modoboa/core/tests/test_views.py
modoboa/core/views/dashboard.py
test_project/test_project/settings.py

Resolves #1797 
Modoboa server is behind proxy, so no internet direct access
Acces dashboard via admin account
-> 504 Gateway Time-out
It is possible to disable RSS requests in settings.py file being behind a proxy to avoid the dashboard time-out.

Adding setting to disable RSS requests.

---

Dockerfile.dev

- Decrease Dockefile image from 637MB to 294MB, leveraging Docker Multi-Stage technique.

Convert Dockerfile to Multi-Stage

---

doc/manual_installation/modoboa.rst

This updates commands for Python 3, improves rendering and code highlighting, completes database commands and adds a note for `--system-site-packages` usage.
By the way, do you know more precisely for which Python package each system package is required? I just make a fresh installation using system package for PostgreSQL and without the need to build any package.

Update and improve manual installation of Modoboa

---

requirements.txt

fixes #1875
failed when running mx check on python 3.8
mx check works again

bump gevent to 1.5.0

---

doc/installation.rst

As discussed on https://github.com/modoboa/modoboa/issues/1992#issuecomment-673392601 new administrators that only look at the documentation page for the modoboa installer will not notice the fixed Python 3 requirement.
The documentation does not provide Python 3 as modoboa requirement.
The documentation provides Python 3 as fixed modoboa requirement and also nots about when the change did come.

Provide Python 3 requirement hints on documentation

---

.github/workflows/modoboa.yml

The tests are currently broken since the image provided by Github is not up-to-date:
```
...
Err:4 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libsasl2-dev amd64 2.1.27~101-g0780600+dfsg-3ubuntu2.1
404  Not Found [IP: 52.147.219.192 80]
Fetched 2139 kB in 0s (10.1 MB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/cyrus-sasl2/libsasl2-dev_2.1.27~101-g0780600+dfsg-3ubuntu2.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
This ensure that the package index is synchronized before installing anything.

Resynchronize the package index in tests

---

doc/configuration.rst
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/password_hashers/__init__.py
modoboa/core/tests/test_authentication.py
setup.cfg

Dovecot is not a hard-dependency of Modoboa, thus it could be installed and running on another host or container - i.e. for isolation reasons. This PR allows one to define - strong - password schemes to use in this case and document the related variables available in the settings.
If `doveadm` binary is not found on the host, the only password scheme which will be available - and use - will be `{PLAIN}` - which means that password will be stored in clear. There is no alternative to define a *fake* `doveadm` binary - as it is done in tests - to mimic the output and tell Modoboa which schemes are supported - which I think it is not a real and clean solution since Modoboa is at least calling `doveadm` with other arguments.
Password must never be stored in clear, so MD5-CRYPT is added to the …

Prevent that password are stored in plain-text

---

doc/manual_installation/modoboa.rst
requirements.txt

The Debian package `python-rrdtool` in Buster uses the Python binding provided by `rrdtool`. Even if the current version is 0.1.10, `rrdtool` version is 1.7.1 which should already include required features - e.g. export functions regarding the [changelog](https://github.com/oetiker/rrdtool-1.x/blob/master/CHANGES). Finally, regarding the ["changelog"](https://github.com/commx/python-rrdtool/releases) of the separated `rrdtool` package which is in PyPi, it does not include relevant features or fixes.

Accept rrdtool version in Debian Buster

---

modoboa/admin/lib.py

get_dns_records() could be fed with a name that is too long for the DNS
protocol. In this case a NameTooLong error is thrown, which we can catch
and log an error for. This can happen for example if a DNS name that is
already at the limit is used in combination with "manage.py modo
check_mx", which appends an autodiscover to the domain, which then
exceeds the DNS name limit.
`manage.py modo check_mx` crashes each time I run it, errors out with a NameTooLong error.
Crash
No crash, an error is logged instead.

Handle NameTooLong by logging an error

---

modoboa/admin/api.py
modoboa/admin/tests/test_api.py
modoboa/lib/viewsets.py
modoboa/relaydomains/viewsets.py

Creation, update and deletion of an object is currently not logged when it is done through the API.
The `create()`, `update()` and `delete()` methods of `rest_framework.viewsets.ModelViewSet` do not create a revision, which do not produce the corresponding log message creation - see `modoboa.core.handlers.post_revision_commit`.
This simply adds a new `modoboa.libs.viewsets.RevisionModelMixin` mixin - sorry, it will produce a conflict with the refacto/vuejs_interface branch - which inherits from [`reversion.views.RevisionMixin`](https://django-reversion.readthedocs.io/en/stable/views.html#reversion-views-revisionmixin). This will decorate the `dispatch()` method to wrap every request in a revision block.
The following can be discussed:
- Is it a good idea to rely on …

Wrap ModelViewSet requests to a revision block

---

modoboa/admin/api/v2/viewsets.py
modoboa/core/api/v1/viewsets.py
modoboa/core/drf_authentication.py
modoboa/parameters/api/v2/viewsets.py

This fixes the following error and warnings reported by drf-speculator:
```
Error #0: AccountViewSet: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Ignoring view for now.
Warning #1: AccountViewSet: could not resolve authenticator <class 'modoboa.core.drf_authentication.JWTAuthenticationWith2FA'>. There was no OpenApiAuthenticationExtension registered for that class. Try creating one by subclassing it. Ignoring for now.
```

Fixed some warnings reported by drf-speculator

---

doc/contributing/getting_started.rst
doc/manual_installation/modoboa.rst
doc/manual_installation/webserver.rst
doc/upgrade.rst
modoboa/core/templates/core/dashboard.html

- Modify the Upgrade notice for the 2.0-beta1 version to separate the new interface part - and add a note about its work in progress state. The NGINX configuration is also moved there in order to prevent to serve this new interface unintentionally while it is not stable yet.
- Reorganize and complete the _How to contribute_ section for the new interface.
- Show the new admin banner in the dashboard to admins only

Some documentation and fix for the new interface

---

frontend/public/config.json
frontend/src/api/repository.js
frontend/src/main.js
frontend/vue.config.js

Those changes allows one to run development servers for the API and the frontend without the need to configure CORS headers. They are otherwise required since the frontend and the API are not server on the same base URL since the ports are not the same.
By the way, the `baseUrl` option for axios is also defined when the configuration is fetched and an error is raised if `API_BASE_URL` is missing.

Proxify API requests in Vue's development server

---

frontend/package.json
frontend/public/index.html
frontend/src/plugins/vuetify.js
frontend/src/styles/global.scss
frontend/src/styles/variables.scss
frontend/yarn.lock

For at least privacy and performance gains - see [Fontsource introduction](https://fontsource.org/docs/introduction) - this replaces requests to CDN for Material Design Icons and Rubik font by NPM packages to self-host them.

Self-host icons and fonts in new frontend

---

doc/contributing/plugin_api.rst

Django's 1.9 documentation is no longer accessible, updating to the updated documentation for Django 2.2, used by modoboa.

Fix broken django doc. link in plugin_api.rst

---

modoboa/admin/forms/account.py
modoboa/admin/models/alias.py
modoboa/admin/tests/test_account.py

#2399
- Exception and failure during account creation or update.
- No failure.
- Extension of the recipients of the Alias in order to record the account.
Fix #2399.

Fix account alias on legacy interface

---

doc/manual_installation/webserver.rst

Description of the issue:
<modoboa dir> is not only wrong, it was also misleading, fixed doc
Current behavior before PR: 
<modoboa dir> in gunicorn installation was misleading
no misleading, since the correct way is giving the instance/app name which is used during deployment!

fix <modoboa dir> to APP NAME

---

modoboa/core/templates/core/robots.txt
modoboa/core/urls.py

Hi !
This PR addresses the issue #1612 by adding a robots.txt file that denies access to Modoboa's web interface. 
Currently search engines are allowed to index every crawlable modoboa file. This new robots.txt file would prevent any page from being indexed, which is probably a good thing as pointed out by the original issue. 
Please let me know if you think of ways to improve this PR.

Adding a restrictive robot.txt file

---

doc/manual_installation/dovecot.rst

This updates the SQL queries of Dovecot to check if the user and the domain are enabled. It mainly fixes https://github.com/modoboa/modoboa/issues/2120 when Dovecot LMTP is used for Postfix SASL.

Update documentation for Dovecot's authentication configuration

---

doc/manual_installation/modoboa.rst

Our environment sends over 50,000 emails per day. Even with dividing dovecots and postfix log and daily rotate, you'll still end up in 80MB log files easily. This causes huge CPU spikes the bigger the log file gets. Eventually this will cause all of your system cores to be under extremely high load causing the whole system to be slow.
This is also shown in this discussion:
https://github.com/modoboa/modoboa/discussions/2031
and this isuse:
https://github.com/modoboa/modoboa/issues/1187
For context, here's the systems load over 30 days - you can clearly see when we switched to once per day which is why I believe the hint I've added is very useful for others.
Logparsing was entirely missing from the crontab. No …

Maintenance: Add missing log parse parts plus hint

---

modoboa/policyd/management/commands/policy_daemon.py

see issue #2562 and #2561. 
From python 3.10, start_server() doesn't take[ ``loop`` as an argument ](https://docs.python.org/3.10/library/asyncio-stream.html#asyncio.start_server). As a result, it is tedious to use it on Ubuntu 22.04. 
Policy deamon keep crashing due to a TypeError making it impossible to receive/send mails.
Have it compatible with python 3.10. 
!!!!! I've just deleted a line, and I'm not sure if this was the right thing to do, however, I can now send mails !

Fix depreciation from python 3.10

---

modoboa/lib/email_utils.py

see #2572 
HTML emails would be dumped into ``/tmp/output.txt``. I didn't find any call for this file. Considering it useless.

removed html dump to file

---

modoboa/admin/app_settings.py
modoboa/core/api/v2/serializers.py
modoboa/core/api/v2/tests.py
modoboa/core/sms_backends/ovh.py

fixes #2559 
User can now save core parameters on new-admin.

Fixed core parameters unable to save on v2

---

.gitignore
frontend/src/components/parameters/ParametersForm.vue
modoboa/parameters/api/v2/viewsets.py
modoboa/parameters/tools.py

In order to prepare work for migrating modoboa's plugins parameters to vue interface, this PR enables dynamic setting labeling (instead of a hard-coded one).

Dynamic parameter label vue

---

modoboa/core/management/commands/generate_postfix_maps.py

Description of the issue/feature this PR addresses: #2608 
port is not appended to host (see [mysql_table](http://www.postfix.org/mysql_table.5.html) and [pgsql_table](https://www.postfix.org/pgsql_table.5.html))
```
user = v-kubernet-mail_mod-x
password = y
dbname = modoboa
hosts = pgbouncer.db
query = SELECT service || ':' || next_hop FROM transport_transport WHERE pattern='%s'
```
```
user = v-kubernet-mail_mod-x
password = y
dbname = modoboa
hosts = pgbouncer.db:6432
query = SELECT service || ':' || next_hop FROM transport_transport WHERE pattern='%s'
```

fix: use dbport settings in generate_postfix_map

---

frontend/src/components/domains/DKIMKeyViewer.vue
frontend/src/components/domains/DNSDetail.vue
frontend/src/components/domains/DomainDKIMKey.vue
modoboa/admin/static/admin/css/admin.css
modoboa/admin/templates/admin/_domain_dkim_key.html
modoboa/admin/templates/admin/domain_detail.html

- To make it easier to set DKIM key, you can now one-click copy dkim key to clipboard (in raw or bind format). Display of the keys has also been improved on GUIv2.
- Added a dialog before regenerating DKIM keys to prevent non-wanted regeneration (#2610)

ability to copy dkim key and warning before regenerate

---

modoboa/admin/management/commands/subcommands/_mx.py
modoboa/admin/tests/test_mx.py

Kind of same mitigation as modoboa/modoboa-installer#426 but for dnsbl check. 
I would be more in favor to simply drop spamhaus from dnsbl provider, but this could be a simple mitigation in case the user didn't set a dns resolver with rDNS.

Mitigate spamhaus dns fail while querying for dnsbl

---

frontend/src/components/domains/DNSDetail.vue

Improved UX by showing pending labels on dns details for domain page when status is pending.
see #2614.

Show pending label when check is pending on GUIv2

---

frontend/src/components/tools/TimeSerieChart.vue

Having an empty color made ApexCharts crash.

Fixed statistics empty on GUIv2

---

.github/workflows/modoboa.yml
requirements.txt
tox.ini

`py-dateutil` is abandoned, it hasn't been touched since 2014. With Python 3.10, I receive errors like: `module 'collections' has no attribute 'Callable'`.
`python-dateutil` seems to be the maintained fork of `py-dateutil`, and a drop-in replacement. Test suite runs equally with or without the changed dependency.
```
Environment:
Request Method: GET
Request URL: https://modoboa.example.net/dashboard/
Django Version: 3.2.16
Python Version: 3.10.6
Installed Applications:
('django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.sites',
'django.contrib.staticfiles',
'reversion',
'ckeditor',
'ckeditor_uploader',
'rest_framework',
'rest_framework.authtoken',
'drf_spectacular',
'phonenumber_field',
'django_otp', …
```

Replace py-dateutil with python-dateutil

---

doc/rest_api.rst

Description of the issue/feature this PR addresses: new API route v2-swagger
Current behavior before PR: showing page does not exist in demo page
Desired behavior after PR is merged: points to new url

updated docs to new api

---

doc/installation.rst
doc/moving.rst
doc/upgrade.rst

hope this is sufficient, else let me know if you would change something. Bash won't be a login shell but since we clear the enviroment with ``sudo -i`` this should not have any meaningful impact

docs: run bash explicitly for migration

---

doc/rest_api.rst
doc/upgrade.rst
modoboa/core/commands/deploy.py
modoboa/core/commands/templates/settings.py.tpl
modoboa/core/context_processors.py
test_project/test_project/settings.py

* Added instructions to update the frontend manually.
* Fixed a few formatting errors across the documentation.
* Fixed the default new-admin url from `new_admin` to `new-admin` (true default).

Update frontend doc and fix new admin default url

---

modoboa/admin/management/commands/subcommands/_export.py

It causes errors at import time and internal aliases will be recreated automatically.

Do not export internal aliases

---

frontend/package.json
frontend/src/components/alarms/AlarmList.vue
frontend/src/components/logs/AuditTrailList.vue
frontend/src/components/logs/MessageList.vue
frontend/yarn.lock

On the new admin interface, add delay when performing a search request to the server to avoid too many requests and risking being throttled.
Each new character in the field would fire a request to the server
A delay of 500ms is applied before firing a new request

Add delay for server search requests

---

doc/upgrade.rst

It's just a `.` rather than a `_`. 
I copied this line and ran into an 500 Internal server error after login and needed to figure out why via `DEBUG=True` because there where no logs found anywhere pointing to that error.
Logging in is possible again.

Update upgrade.rst imap_migration module fix.

---

docker/Dockerfile.dev
frontend/package.json
frontend/src/api/account.js
frontend/src/components/user/TwoFactorAuthForm.vue
frontend/src/plugins/vee-validate.js
frontend/src/views/TwoFA.vue
frontend/yarn.lock
modoboa/core/api/v1/serializers.py
modoboa/core/api/v1/viewsets.py
modoboa/core/api/v2/tests.py
modoboa/core/api/v2/viewsets.py
modoboa/core/templates/core/user_security.html
modoboa/core/tests/test_viewsets.py
modoboa/static/js/twocols_nav.js

- Added password verification when editing TFA setup ( disable and reset backup codes).
- Added a click to copy button to copy the key directly
- Changed api to send the url of the TOTP instead of the QRcode (to send the key as well), the QR code is now generated on the frontend (client side)
- On frontend added length check to form validation
- Updated tests

Tfa setup improvement

---

.github/workflows/modoboa.yml
modoboa/policyd/core.py
modoboa/policyd/tests.py
requirements.txt
test-requirements.txt

Policyd part crash on debian 12
The policyd supervisor crash with a well known bug on aioredis with python 3.11. Like I found [here](https://github.com/aio-libs/aioredis-py/issues/1443), aioredis is not maintained anymore, but we can replace it by redis with asyncio (with redis >= 4.2.0rc1)
I made the change and all seems to work well with python 3.11, but we should want more testers!

Use asyncio from redis instead of aioredis to make app python 3.11 compatible

---

frontend/src/components/identities/AccountAliasForm.vue
frontend/src/components/identities/AccountCreationForm.vue
frontend/src/components/identities/AccountForm.vue
frontend/src/components/identities/AliasCreationForm.vue
frontend/src/components/tools/ImportForm.vue
frontend/src/mixins/importExport.js
frontend/src/views/identities/Identities.vue
modoboa/admin/api/v2/serializers.py
modoboa/admin/api/v2/tests.py
modoboa/admin/api/v2/viewsets.py
modoboa/admin/lib.py
modoboa/admin/management/commands/subcommands/_import.py
modoboa/admin/models/__init__.py
modoboa/admin/models/alias.py
modoboa/admin/tests/test_data/import_aliases.csv
modoboa/admin/tests/test_import_.py
modoboa/core/commands/templates/urls.py.tpl
modoboa/core/extensions.py
modoboa/lib/exceptions.py

- Fix Admin not able to add alias with the user creation wizard
- Changed behavior of aliases creation in general : trying to create an already existing alias will simply add the recipient to the existing one silently
- Using continue-if-exists option on alias import from csv will now modify the alias instead of throwing an error (because of bad formatting). Without the option, the error will be thrown
- Improved error message regarding alias creation/modification/importation
- Trying to create an already existing alias on new admin will automatically redirect to the edit page of said alias

Improved alias management

---

modoboa/templates/registration/login.html

If the network is terrible, the user clicks rapidly and many times, it will show a CSRF error because the last time click had the wrong CSRF token.
You can click the login button multiple times in the login page to submit multiple times to the login api.
after you click one time, the submit button be disabled. after the current request has been processed, you can click again.

to avoid CSRF error due to multiple click

---

doc/upgrade.rst
modoboa/core/commands/templates/settings.py.tpl

Fixes #3241.
Can't get Modoboa working with Redis socket.
Using Redis socket is fixed in `settings.py` and documented.

Documenting use of Redis socket and fixing configuration

---

doc/moving.rst
modoboa/imap_migration/templates/imap_migration/offlineimap.conf

By using mailbox instead of username for local account configuration, we ensure that the username is valid, even if it was renamed.
fix #2980

Make sure to use local address when generating offlineimap config

---

ldap-requirements.txt
modoboa/lib/tests/test_email_utils.py

RFC 2822 [states that the separator for mailboxes is the comma](https://datatracker.ietf.org/doc/html/rfc2822#section-3.6.2) however the test tries with a semi-column. It used to work but was fixed as part of the [CVE-2023-27043](https://nvd.nist.gov/vuln/detail/CVE-2023-27043).
As far as I checked, the webmail do use the comma as a separator in the webmail...

Fixed addresses test not aligned with RFC 2822

---

modoboa/core/migrations/0025_rename_user_email_is_active_core_user_email_c0c03f_idx.py

It seems that the rename index is not needed

Try to fix outdated migration

---

modoboa/core/migrations/0025_rename_user_email_is_active_core_user_email_c0c03f_idx.py

Ref : #3670 
It seems that although no SQL is executed, django does want this migration to be included. 
Perhaps the fix should be by extending the Migration class and bypassing the exception for sqlite ?

Revert "Try to fix outdated migration"
